/**
 * YOLOv2 FPGA Accelerator - Linux Configuration Header
 * 
 * Hardware addresses and register offsets for the KV260 platform.
 * These addresses are fixed in the Vivado block design.
 * 
 * IMPORTANT: Register offsets must match the HLS-generated xyolo2_fpga_hw.h
 */

#ifndef YOLO2_CONFIG_H
#define YOLO2_CONFIG_H

#include <stdint.h>

/*===========================================================================
 * Base Addresses (from Vivado Address Editor)
 *===========================================================================*/
#define YOLO2_CTRL_BASE        0xA0000000UL  // Accelerator control registers
#define AXI_GPIO_QW_BASE       0xA0010000UL  // Weight quantization Q value
#define AXI_GPIO_QA_IN_BASE    0xA0020000UL  // Input activation Q value
#define AXI_GPIO_QA_OUT_BASE   0xA0030000UL  // Output activation Q value
#define AXI_GPIO_QB_BASE       0xA0040000UL  // Bias Q value

// Memory region sizes for mmap
#define YOLO2_CTRL_SIZE        0x1000   // 4KB for control registers
#define AXI_GPIO_SIZE          0x1000   // 4KB per GPIO

/*===========================================================================
 * AXI GPIO Register Offsets
 *===========================================================================*/
#define GPIO_DATA_OFFSET       0x00     // Data register
#define GPIO_TRI_OFFSET        0x04     // Tri-state control

/*===========================================================================
 * HLS-Generated Control Register Offsets
 * FROM: xyolo2_fpga_hw.h (generated by Vitis HLS)
 *===========================================================================*/
#define CTRL_AP_CTRL           0x00     // Control register
#define CTRL_AP_START          (1 << 0) // Start bit
#define CTRL_AP_DONE           (1 << 1) // Done bit (Clear on Read!)
#define CTRL_AP_IDLE           (1 << 2) // Idle bit
#define CTRL_AP_READY          (1 << 3) // Ready bit (Clear on Read!)
#define CTRL_AP_CONTINUE       (1 << 4) // Continue bit (for auto-restart)
#define CTRL_AP_AUTO_RESTART   (1 << 7) // Auto-restart mode

#define CTRL_GIE_OFFSET        0x04     // Global Interrupt Enable
#define CTRL_IER_OFFSET        0x08     // IP Interrupt Enable Register
#define CTRL_ISR_OFFSET        0x0c     // IP Interrupt Status Register

// 64-bit address registers (low 32 bits at offset, high 32 bits at offset+4)
#define CTRL_INPUT_OFFSET      0x10     // Input buffer address (64-bit)
#define CTRL_OUTPUT_OFFSET     0x1c     // Output buffer address (64-bit) - NOT 0x18!
#define CTRL_WEIGHT_OFFSET     0x28     // Weight buffer address (64-bit)
#define CTRL_BETA_OFFSET       0x34     // Beta/bias buffer address (64-bit)

// 32-bit parameter registers
#define CTRL_IFM_NUM_OFFSET    0x40     // Input feature map channels
#define CTRL_OFM_NUM_OFFSET    0x48     // Output feature map channels
#define CTRL_KSIZE_OFFSET      0x50     // Kernel size
#define CTRL_KSTRIDE_OFFSET    0x58     // Kernel stride
#define CTRL_INPUT_W_OFFSET    0x60     // Input width
#define CTRL_INPUT_H_OFFSET    0x68     // Input height
#define CTRL_OUTPUT_W_OFFSET   0x70     // Output width
#define CTRL_OUTPUT_H_OFFSET   0x78     // Output height
#define CTRL_PADDING_OFFSET    0x80     // Padding size
#define CTRL_ISNL_OFFSET       0x88     // Is non-linear (activation)
#define CTRL_ISBN_OFFSET       0x90     // Is batch normalized
#define CTRL_TM_OFFSET         0x98     // Tile M
#define CTRL_TN_OFFSET         0xa0     // Tile N
#define CTRL_TR_OFFSET         0xa8     // Tile R (rows)
#define CTRL_TC_OFFSET         0xb0     // Tile C (columns)
#define CTRL_OFM_NUM_BOUND_OFFSET  0xb8 // OFM bound
#define CTRL_MLOOPSXTM_OFFSET  0xc0     // mLoops * TM
#define CTRL_MLOOPS_A1XTM_OFFSET 0xc8   // (mLoops+1) * TM
#define CTRL_LAYER_TYPE_OFFSET 0xd0     // Layer type

// NOTE: Q values are passed via AXI GPIO, not control registers
// The HLS IP does not have Q value registers in CTRL_BUS

/*===========================================================================
 * Memory Configuration
 *===========================================================================*/
// Buffer sizes (in 16-bit words)
#define MEM_LEN                6922240  // Main inference buffer
#define INPUT_DEPTH_WORDS      6922240  // Input buffer capacity
#define OUTPUT_DEPTH_WORDS     5537792  // Output buffer capacity
#define MEMORY_ALIGNMENT       4096     // 4KB alignment for AXI/DMA

// Weight buffer sizes (in bytes for INT16 mode)
#define WEIGHTS_SIZE_BYTES     (50941792 * 2)  // ~97MB weights
#define BIAS_SIZE_BYTES        (10761 * 2)     // ~21KB bias

/*===========================================================================
 * Tiling Parameters (must match HLS design)
 *===========================================================================*/
// Keep these in sync with `hls/core/params.hpp` used to build the HLS IP.
#define Tm                     28       // Output channel tile (max)
#define Tn                     4        // Input channel tile (max)
#define Tr                     26       // Row tile (max)
#define Tc                     32       // Column tile (max)
#define OnChipIB_Height        53       // On-chip input buffer height
#define OnChipIB_Width         65       // On-chip input buffer width

/*===========================================================================
 * Network Dimensions
 *===========================================================================*/
#define INPUT_WIDTH            416
#define INPUT_HEIGHT           416
#define INPUT_CHANNELS         3
#define INPUT_ELEMS            (INPUT_WIDTH * INPUT_HEIGHT * INPUT_CHANNELS)

/*===========================================================================
 * Layer Types
 *===========================================================================*/
#define CONVOLUTIONAL          0
#define MAXPOOL                1
#define REORG                  2
#define ROUTE                  3
#define REGION                 4

// Activation types
#define LEAKY                  1

/*===========================================================================
 * File Paths (Linux filesystem)
 *===========================================================================*/
#define DEFAULT_WEIGHTS_PATH   "/home/ubuntu/weights/weights_reorg_int16.bin"
#define DEFAULT_BIAS_PATH      "/home/ubuntu/weights/bias_int16.bin"
#define DEFAULT_WEIGHT_Q_PATH  "/home/ubuntu/weights/weight_int16_Q.bin"
#define DEFAULT_BIAS_Q_PATH    "/home/ubuntu/weights/bias_int16_Q.bin"
#define DEFAULT_IOFM_Q_PATH    "/home/ubuntu/weights/iofm_Q.bin"
#define DEFAULT_CONFIG_PATH    "/home/ubuntu/config/yolov2.cfg"
#define DEFAULT_LABELS_PATH    "/home/ubuntu/config/coco.names"
#define DEFAULT_IMAGE_PATH     "/home/ubuntu/test_images/dog.jpg"

/*===========================================================================
 * Execution Configuration
 *===========================================================================*/
// Default per-layer watchdog timeout for the accelerator.
// Override at runtime with the `YOLO2_LAYER_TIMEOUT_MS` environment variable.
#define YOLO2_LAYER_TIMEOUT_MS 60000U

/*===========================================================================
 * Return Codes
 *===========================================================================*/
#define YOLO2_SUCCESS          0
#define YOLO2_ERROR           -1
#define YOLO2_TIMEOUT         -2
#define YOLO2_INIT_ERROR      -3
#define YOLO2_MMAP_ERROR      -4
#define YOLO2_DMA_ERROR       -5

#endif /* YOLO2_CONFIG_H */
