#!/usr/bin/env python3
"""
Hardware Parameter Generator for YOLOv2 Accelerator

This script generates hardware-specific parameters for FPGA acceleration.
It creates header files with tiling parameters (Tn, Tm, Tr, Tc) that control
the hardware accelerator's on-chip buffer dimensions and processing tile sizes.

Parameters:
    S: Stride
    K: Kernel size
    Tn: Tiling parameter for input channels
    Tm: Tiling parameter for output channels
    Tr: Tiling parameter for rows
    Tc: Tiling parameter for columns
    
Note: This script is primarily used when preparing for hardware acceleration.
For CPU-only inference, default parameters are sufficient.
"""

import sys
import os

# Hardware tiling parameters
S = 2
K = 3
MAX_BETA_LENGTH = 1024

Tn = 4
Tm = 28
Tr = 26
Tc = 32
OnChipIB_Width = (Tc-1)*S+K
OnChipIB_Height = (Tr-1)*S+K
TRow_max = OnChipIB_Height
TCol_max = OnChipIB_Width

params_hpp = f"""#pragma once

// Auto-generated hardware parameter header. Do not edit by hand.
// Generated by scripts/hw_params_gen.py

constexpr int S = {S};
constexpr int K = {K};
constexpr int MAX_BETA_LENGTH = {MAX_BETA_LENGTH};
constexpr int Tn = {Tn};
constexpr int Tm = {Tm};
constexpr int Tr = {Tr};
constexpr int Tc = {Tc};
constexpr int OnChipIB_Width = {OnChipIB_Width};
constexpr int OnChipIB_Height = {OnChipIB_Height};
constexpr int TRow_max = {TRow_max};
constexpr int TCol_max = {TCol_max};
"""

with open("hls/core/params.hpp", "w", encoding="utf-8") as f:
    f.write(params_hpp)

print(params_hpp)
print("Hardware parameter file generated: hls/core/params.hpp")
