#!/usr/bin/env python3
"""
Hardware Parameter Generator for YOLOv2 Accelerator.

Generates `hls/core/params.hpp` (or a custom output path) from tile parameters.
Defaults preserve the current baseline used in this repository.
"""

from __future__ import annotations

import argparse
from pathlib import Path
import re


DEFAULT_S = 2
DEFAULT_K = 3
DEFAULT_MAX_BETA_LENGTH = 1024
DEFAULT_TN = 4
DEFAULT_TM = 32
DEFAULT_TR = 13
DEFAULT_TC = 13
DEFAULT_OUTPUT = "hls/core/params.hpp"
DEFAULT_LINUX_CONFIG = "linux_app/include/yolo2_config.h"


def _positive_int(name: str, value: int) -> None:
    if value <= 0:
        raise ValueError(f"{name} must be > 0 (got {value})")


def _render_header(
    *,
    stride: int,
    kernel: int,
    max_beta_length: int,
    tn: int,
    tm: int,
    tr: int,
    tc: int,
) -> str:
    onchip_ib_width = (tc - 1) * stride + kernel
    onchip_ib_height = (tr - 1) * stride + kernel
    trow_max = onchip_ib_height
    tcol_max = onchip_ib_width

    return f"""#pragma once

// Auto-generated hardware parameter header. Do not edit by hand.
// Generated by scripts/hw_params_gen.py

constexpr int S = {stride};
constexpr int K = {kernel};
constexpr int MAX_BETA_LENGTH = {max_beta_length};
constexpr int Tn = {tn};
constexpr int Tm = {tm};
constexpr int Tr = {tr};
constexpr int Tc = {tc};
constexpr int OnChipIB_Width = {onchip_ib_width};
constexpr int OnChipIB_Height = {onchip_ib_height};
constexpr int TRow_max = {trow_max};
constexpr int TCol_max = {tcol_max};
"""


def _sync_linux_config(
    *,
    config_path: Path,
    tm: int,
    tn: int,
    tr: int,
    tc: int,
    onchip_ib_width: int,
    onchip_ib_height: int,
) -> None:
    if not config_path.exists():
        raise FileNotFoundError(f"Linux config header not found: {config_path}")

    text = config_path.read_text(encoding="utf-8")
    replacements = [
        ("Tm", tm),
        ("Tn", tn),
        ("Tr", tr),
        ("Tc", tc),
        ("OnChipIB_Height", onchip_ib_height),
        ("OnChipIB_Width", onchip_ib_width),
    ]
    for macro, value in replacements:
        pattern = re.compile(rf"(^\s*#define\s+{re.escape(macro)}\s+)(\d+)(\b.*$)", re.MULTILINE)
        text, count = pattern.subn(rf"\g<1>{value}\g<3>", text, count=1)
        if count == 0:
            raise ValueError(f"Could not find macro '{macro}' in {config_path}")

    config_path.write_text(text, encoding="utf-8")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate hls/core/params.hpp from tiling parameters."
    )
    parser.add_argument("--tn", type=int, default=DEFAULT_TN, help=f"Input-channel tile (default: {DEFAULT_TN})")
    parser.add_argument("--tm", type=int, default=DEFAULT_TM, help=f"Output-channel tile (default: {DEFAULT_TM})")
    parser.add_argument("--tr", type=int, default=DEFAULT_TR, help=f"Row tile (default: {DEFAULT_TR})")
    parser.add_argument("--tc", type=int, default=DEFAULT_TC, help=f"Column tile (default: {DEFAULT_TC})")
    parser.add_argument("--stride", type=int, default=DEFAULT_S, help=f"Stride S (default: {DEFAULT_S})")
    parser.add_argument("--kernel", type=int, default=DEFAULT_K, help=f"Kernel size K (default: {DEFAULT_K})")
    parser.add_argument(
        "--max-beta-length",
        type=int,
        default=DEFAULT_MAX_BETA_LENGTH,
        help=f"MAX_BETA_LENGTH (default: {DEFAULT_MAX_BETA_LENGTH})",
    )
    parser.add_argument(
        "--output",
        default=DEFAULT_OUTPUT,
        help=f"Output header path (default: {DEFAULT_OUTPUT})",
    )
    parser.add_argument(
        "--linux-config",
        default=DEFAULT_LINUX_CONFIG,
        help=f"Linux config header path to keep in sync (default: {DEFAULT_LINUX_CONFIG})",
    )
    parser.add_argument(
        "--no-sync-linux-config",
        action="store_true",
        help="Do not update linux_app/include/yolo2_config.h macros.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    _positive_int("tn", args.tn)
    _positive_int("tm", args.tm)
    _positive_int("tr", args.tr)
    _positive_int("tc", args.tc)
    _positive_int("stride", args.stride)
    _positive_int("kernel", args.kernel)
    _positive_int("max_beta_length", args.max_beta_length)

    header_text = _render_header(
        stride=args.stride,
        kernel=args.kernel,
        max_beta_length=args.max_beta_length,
        tn=args.tn,
        tm=args.tm,
        tr=args.tr,
        tc=args.tc,
    )

    output_path = Path(args.output)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(header_text, encoding="utf-8")

    print(header_text)
    print(f"Hardware parameter file generated: {output_path}")

    if not args.no_sync_linux_config:
        onchip_ib_width = (args.tc - 1) * args.stride + args.kernel
        onchip_ib_height = (args.tr - 1) * args.stride + args.kernel
        linux_config_path = Path(args.linux_config)
        _sync_linux_config(
            config_path=linux_config_path,
            tm=args.tm,
            tn=args.tn,
            tr=args.tr,
            tc=args.tc,
            onchip_ib_width=onchip_ib_width,
            onchip_ib_height=onchip_ib_height,
        )
        print(f"Linux config synchronized: {linux_config_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
